version: '3'

services:
  flask-test:
    build: .
    container_name: flask-test
    expose:
      - "5000"
  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - flask-test
